name: Build C# EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Build EXE
      run: |
        dotnet publish OcrTcpToKeyboard2.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: OcrTcpToKeyboard
        path: bin/Release/net6.0/win-x64/publish/OcrTcpToKeyboard2.exe
